{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "b20d44bb-03a8-4be5-b4ff-52b68a3a414f",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 244 entries, 0 to 243\n",
      "Data columns (total 7 columns):\n",
      " #   Column      Non-Null Count  Dtype   \n",
      "---  ------      --------------  -----   \n",
      " 0   total_bill  244 non-null    float64 \n",
      " 1   tip         244 non-null    float64 \n",
      " 2   sex         244 non-null    category\n",
      " 3   smoker      244 non-null    category\n",
      " 4   day         244 non-null    category\n",
      " 5   time        244 non-null    category\n",
      " 6   size        244 non-null    int64   \n",
      "dtypes: category(4), float64(2), int64(1)\n",
      "memory usage: 7.4 KB\n",
      "None\n",
      "Fitting 4 folds for each of 5 candidates, totalling 20 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_search.py:305: UserWarning:\n",
      "\n",
      "The total space of parameters 5 is smaller than n_iter=10. Running 5 iterations. For exhaustive searches, use GridSearchCV.\n",
      "\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "\nAll the 20 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n5 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 345, in fit\n    X, y = self._validate_data(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\base.py\", line 584, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1106, in check_X_y\n    X = check_array(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 902, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[32.9  28.97 34.83 50.81 12.66 21.01 16.31 27.05 13.81 15.77 12.43 13.39\n 10.33 35.26 35.83 12.69 14.07 24.59 14.26 15.06 34.3  31.85 16.   11.02\n  8.51 11.38 12.16 40.55 12.02 16.47 17.59 30.4  30.14 16.04 15.95 39.42\n 45.35  9.6  16.66 31.27 20.53 32.4  22.75 20.69  9.68  8.35 15.69 23.68\n 15.36  9.94 12.26 13.42 32.83 10.09 18.04 13.81 19.44 17.78 12.74 26.88\n 15.81 14.   22.49 32.68 11.59  8.58 21.16 15.04 18.43 48.27 12.76 20.27\n 16.29 20.76 26.86 11.61 18.26 13.51 13.42 18.29 25.56 25.21 12.54 24.01\n 16.82 48.33 23.1  27.18 12.9  10.63 11.24 28.55 24.71 20.29 26.41 16.4\n 21.5  12.6  30.46 19.81 22.82 16.93 25.   22.12 10.34 34.81  7.51 19.08\n 13.13 22.42 12.46 29.93 18.28 13.   14.73 28.17 30.06 13.42 18.78 17.92\n 18.15 17.07 20.49 14.83  5.75 34.63 44.3 ].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n5 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 345, in fit\n    X, y = self._validate_data(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\base.py\", line 584, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1106, in check_X_y\n    X = check_array(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 902, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[15.53 20.45 34.65 25.29 38.01 29.8   9.78 25.71 20.08 11.17 38.73 16.21\n 18.35 15.42 24.06 21.7  13.94 29.03  8.52 16.32 17.51 10.29 40.17 17.47\n 16.58 17.92 17.46 18.24 15.98 22.76 16.43 13.37 10.07 13.27 23.17 15.48\n 16.99 21.01 27.2  22.23 11.35 14.15 11.87 20.69  9.68  8.35 15.69 23.68\n 15.36  9.94 12.26 13.42 32.83 10.09 18.04 13.81 19.44 17.78 12.74 26.88\n 15.81 14.   22.49 32.68 11.59  8.58 21.16 15.04 18.43 48.27 12.76 20.27\n 16.29 20.76 26.86 11.61 18.26 13.51 13.42 18.29 25.56 25.21 12.54 24.01\n 16.82 48.33 23.1  27.18 12.9  10.63 11.24 28.55 24.71 20.29 26.41 16.4\n 21.5  12.6  30.46 19.81 22.82 16.93 25.   22.12 10.34 34.81  7.51 19.08\n 13.13 22.42 12.46 29.93 18.28 13.   14.73 28.17 30.06 13.42 18.78 17.92\n 18.15 17.07 20.49 14.83  5.75 34.63 44.3 ].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n5 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 345, in fit\n    X, y = self._validate_data(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\base.py\", line 584, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1106, in check_X_y\n    X = check_array(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 902, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[15.53 20.45 34.65 25.29 38.01 29.8   9.78 25.71 20.08 11.17 38.73 16.21\n 18.35 15.42 24.06 21.7  13.94 29.03  8.52 16.32 17.51 10.29 40.17 17.47\n 16.58 17.92 17.46 18.24 15.98 22.76 16.43 13.37 10.07 13.27 23.17 15.48\n 16.99 21.01 27.2  22.23 11.35 14.15 11.87 32.9  28.97 34.83 50.81 12.66\n 21.01 16.31 27.05 13.81 15.77 12.43 13.39 10.33 35.26 35.83 12.69 14.07\n 24.59 14.26 15.06 34.3  31.85 16.   11.02  8.51 11.38 12.16 40.55 12.02\n 16.47 17.59 30.4  30.14 16.04 15.95 39.42 45.35  9.6  16.66 31.27 20.53\n 32.4  22.75 48.33 23.1  27.18 12.9  10.63 11.24 28.55 24.71 20.29 26.41\n 16.4  21.5  12.6  30.46 19.81 22.82 16.93 25.   22.12 10.34 34.81  7.51\n 19.08 13.13 22.42 12.46 29.93 18.28 13.   14.73 28.17 30.06 13.42 18.78\n 17.92 18.15 17.07 20.49 14.83  5.75 34.63 44.3 ].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n5 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 345, in fit\n    X, y = self._validate_data(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\base.py\", line 584, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1106, in check_X_y\n    X = check_array(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 902, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[15.53 20.45 34.65 25.29 38.01 29.8   9.78 25.71 20.08 11.17 38.73 16.21\n 18.35 15.42 24.06 21.7  13.94 29.03  8.52 16.32 17.51 10.29 40.17 17.47\n 16.58 17.92 17.46 18.24 15.98 22.76 16.43 13.37 10.07 13.27 23.17 15.48\n 16.99 21.01 27.2  22.23 11.35 14.15 11.87 32.9  28.97 34.83 50.81 12.66\n 21.01 16.31 27.05 13.81 15.77 12.43 13.39 10.33 35.26 35.83 12.69 14.07\n 24.59 14.26 15.06 34.3  31.85 16.   11.02  8.51 11.38 12.16 40.55 12.02\n 16.47 17.59 30.4  30.14 16.04 15.95 39.42 45.35  9.6  16.66 31.27 20.53\n 32.4  22.75 20.69  9.68  8.35 15.69 23.68 15.36  9.94 12.26 13.42 32.83\n 10.09 18.04 13.81 19.44 17.78 12.74 26.88 15.81 14.   22.49 32.68 11.59\n  8.58 21.16 15.04 18.43 48.27 12.76 20.27 16.29 20.76 26.86 11.61 18.26\n 13.51 13.42 18.29 25.56 25.21 12.54 24.01 16.82].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[27], line 33\u001b[0m\n\u001b[0;32m     30\u001b[0m clf \u001b[38;5;241m=\u001b[39m RandomForestRegressor()\n\u001b[0;32m     31\u001b[0m model \u001b[38;5;241m=\u001b[39m RandomizedSearchCV(estimator \u001b[38;5;241m=\u001b[39m clf, param_distributions \u001b[38;5;241m=\u001b[39m random_search, n_iter \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m10\u001b[39m, \n\u001b[0;32m     32\u001b[0m                                cv \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m4\u001b[39m, verbose\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m, random_state\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m101\u001b[39m, n_jobs \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m)\n\u001b[1;32m---> 33\u001b[0m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43my_train\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     35\u001b[0m \u001b[38;5;66;03m# 예측\u001b[39;00m\n\u001b[0;32m     36\u001b[0m y_train_pred \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mpredict(X_train)\n",
      "File \u001b[1;32m~\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_search.py:874\u001b[0m, in \u001b[0;36mBaseSearchCV.fit\u001b[1;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[0;32m    868\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_format_results(\n\u001b[0;32m    869\u001b[0m         all_candidate_params, n_splits, all_out, all_more_results\n\u001b[0;32m    870\u001b[0m     )\n\u001b[0;32m    872\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m results\n\u001b[1;32m--> 874\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_run_search\u001b[49m\u001b[43m(\u001b[49m\u001b[43mevaluate_candidates\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    876\u001b[0m \u001b[38;5;66;03m# multimetric is determined here because in the case of a callable\u001b[39;00m\n\u001b[0;32m    877\u001b[0m \u001b[38;5;66;03m# self.scoring the return type is only known after calling\u001b[39;00m\n\u001b[0;32m    878\u001b[0m first_test_score \u001b[38;5;241m=\u001b[39m all_out[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtest_scores\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n",
      "File \u001b[1;32m~\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_search.py:1768\u001b[0m, in \u001b[0;36mRandomizedSearchCV._run_search\u001b[1;34m(self, evaluate_candidates)\u001b[0m\n\u001b[0;32m   1766\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_run_search\u001b[39m(\u001b[38;5;28mself\u001b[39m, evaluate_candidates):\n\u001b[0;32m   1767\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Search n_iter candidates from param_distributions\"\"\"\u001b[39;00m\n\u001b[1;32m-> 1768\u001b[0m     \u001b[43mevaluate_candidates\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m   1769\u001b[0m \u001b[43m        \u001b[49m\u001b[43mParameterSampler\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m   1770\u001b[0m \u001b[43m            \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mparam_distributions\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mn_iter\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mrandom_state\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrandom_state\u001b[49m\n\u001b[0;32m   1771\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1772\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_search.py:851\u001b[0m, in \u001b[0;36mBaseSearchCV.fit.<locals>.evaluate_candidates\u001b[1;34m(candidate_params, cv, more_results)\u001b[0m\n\u001b[0;32m    844\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(out) \u001b[38;5;241m!=\u001b[39m n_candidates \u001b[38;5;241m*\u001b[39m n_splits:\n\u001b[0;32m    845\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[0;32m    846\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcv.split and cv.get_n_splits returned \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    847\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minconsistent results. Expected \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    848\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msplits, got \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(n_splits, \u001b[38;5;28mlen\u001b[39m(out) \u001b[38;5;241m/\u001b[39m\u001b[38;5;241m/\u001b[39m n_candidates)\n\u001b[0;32m    849\u001b[0m     )\n\u001b[1;32m--> 851\u001b[0m \u001b[43m_warn_or_raise_about_fit_failures\u001b[49m\u001b[43m(\u001b[49m\u001b[43mout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43merror_score\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    853\u001b[0m \u001b[38;5;66;03m# For callable self.scoring, the return type is only know after\u001b[39;00m\n\u001b[0;32m    854\u001b[0m \u001b[38;5;66;03m# calling. If the return type is a dictionary, the error scores\u001b[39;00m\n\u001b[0;32m    855\u001b[0m \u001b[38;5;66;03m# can now be inserted with the correct key. The type checking\u001b[39;00m\n\u001b[0;32m    856\u001b[0m \u001b[38;5;66;03m# of out will be done in `_insert_error_scores`.\u001b[39;00m\n\u001b[0;32m    857\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mcallable\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mscoring):\n",
      "File \u001b[1;32m~\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:367\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[1;34m(results, error_score)\u001b[0m\n\u001b[0;32m    360\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m num_failed_fits \u001b[38;5;241m==\u001b[39m num_fits:\n\u001b[0;32m    361\u001b[0m     all_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[0;32m    362\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mAll the \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    363\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIt is very likely that your model is misconfigured.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    364\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mYou can try to debug the error by setting error_score=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mraise\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    365\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    366\u001b[0m     )\n\u001b[1;32m--> 367\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[0;32m    369\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    370\u001b[0m     some_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[0;32m    371\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mnum_failed_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed out of a total of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    372\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe score on these train-test partitions for these parameters\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    376\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    377\u001b[0m     )\n",
      "\u001b[1;31mValueError\u001b[0m: \nAll the 20 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n5 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 345, in fit\n    X, y = self._validate_data(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\base.py\", line 584, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1106, in check_X_y\n    X = check_array(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 902, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[32.9  28.97 34.83 50.81 12.66 21.01 16.31 27.05 13.81 15.77 12.43 13.39\n 10.33 35.26 35.83 12.69 14.07 24.59 14.26 15.06 34.3  31.85 16.   11.02\n  8.51 11.38 12.16 40.55 12.02 16.47 17.59 30.4  30.14 16.04 15.95 39.42\n 45.35  9.6  16.66 31.27 20.53 32.4  22.75 20.69  9.68  8.35 15.69 23.68\n 15.36  9.94 12.26 13.42 32.83 10.09 18.04 13.81 19.44 17.78 12.74 26.88\n 15.81 14.   22.49 32.68 11.59  8.58 21.16 15.04 18.43 48.27 12.76 20.27\n 16.29 20.76 26.86 11.61 18.26 13.51 13.42 18.29 25.56 25.21 12.54 24.01\n 16.82 48.33 23.1  27.18 12.9  10.63 11.24 28.55 24.71 20.29 26.41 16.4\n 21.5  12.6  30.46 19.81 22.82 16.93 25.   22.12 10.34 34.81  7.51 19.08\n 13.13 22.42 12.46 29.93 18.28 13.   14.73 28.17 30.06 13.42 18.78 17.92\n 18.15 17.07 20.49 14.83  5.75 34.63 44.3 ].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n5 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 345, in fit\n    X, y = self._validate_data(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\base.py\", line 584, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1106, in check_X_y\n    X = check_array(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 902, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[15.53 20.45 34.65 25.29 38.01 29.8   9.78 25.71 20.08 11.17 38.73 16.21\n 18.35 15.42 24.06 21.7  13.94 29.03  8.52 16.32 17.51 10.29 40.17 17.47\n 16.58 17.92 17.46 18.24 15.98 22.76 16.43 13.37 10.07 13.27 23.17 15.48\n 16.99 21.01 27.2  22.23 11.35 14.15 11.87 20.69  9.68  8.35 15.69 23.68\n 15.36  9.94 12.26 13.42 32.83 10.09 18.04 13.81 19.44 17.78 12.74 26.88\n 15.81 14.   22.49 32.68 11.59  8.58 21.16 15.04 18.43 48.27 12.76 20.27\n 16.29 20.76 26.86 11.61 18.26 13.51 13.42 18.29 25.56 25.21 12.54 24.01\n 16.82 48.33 23.1  27.18 12.9  10.63 11.24 28.55 24.71 20.29 26.41 16.4\n 21.5  12.6  30.46 19.81 22.82 16.93 25.   22.12 10.34 34.81  7.51 19.08\n 13.13 22.42 12.46 29.93 18.28 13.   14.73 28.17 30.06 13.42 18.78 17.92\n 18.15 17.07 20.49 14.83  5.75 34.63 44.3 ].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n5 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 345, in fit\n    X, y = self._validate_data(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\base.py\", line 584, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1106, in check_X_y\n    X = check_array(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 902, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[15.53 20.45 34.65 25.29 38.01 29.8   9.78 25.71 20.08 11.17 38.73 16.21\n 18.35 15.42 24.06 21.7  13.94 29.03  8.52 16.32 17.51 10.29 40.17 17.47\n 16.58 17.92 17.46 18.24 15.98 22.76 16.43 13.37 10.07 13.27 23.17 15.48\n 16.99 21.01 27.2  22.23 11.35 14.15 11.87 32.9  28.97 34.83 50.81 12.66\n 21.01 16.31 27.05 13.81 15.77 12.43 13.39 10.33 35.26 35.83 12.69 14.07\n 24.59 14.26 15.06 34.3  31.85 16.   11.02  8.51 11.38 12.16 40.55 12.02\n 16.47 17.59 30.4  30.14 16.04 15.95 39.42 45.35  9.6  16.66 31.27 20.53\n 32.4  22.75 48.33 23.1  27.18 12.9  10.63 11.24 28.55 24.71 20.29 26.41\n 16.4  21.5  12.6  30.46 19.81 22.82 16.93 25.   22.12 10.34 34.81  7.51\n 19.08 13.13 22.42 12.46 29.93 18.28 13.   14.73 28.17 30.06 13.42 18.78\n 17.92 18.15 17.07 20.49 14.83  5.75 34.63 44.3 ].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n\n--------------------------------------------------------------------------------\n5 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\ensemble\\_forest.py\", line 345, in fit\n    X, y = self._validate_data(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\base.py\", line 584, in _validate_data\n    X, y = check_X_y(X, y, **check_params)\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 1106, in check_X_y\n    X = check_array(\n  File \"C:\\Users\\j2hoo\\OneDrive\\Documents\\streamlitbook-evansarah\\venv\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 902, in check_array\n    raise ValueError(\nValueError: Expected 2D array, got 1D array instead:\narray=[15.53 20.45 34.65 25.29 38.01 29.8   9.78 25.71 20.08 11.17 38.73 16.21\n 18.35 15.42 24.06 21.7  13.94 29.03  8.52 16.32 17.51 10.29 40.17 17.47\n 16.58 17.92 17.46 18.24 15.98 22.76 16.43 13.37 10.07 13.27 23.17 15.48\n 16.99 21.01 27.2  22.23 11.35 14.15 11.87 32.9  28.97 34.83 50.81 12.66\n 21.01 16.31 27.05 13.81 15.77 12.43 13.39 10.33 35.26 35.83 12.69 14.07\n 24.59 14.26 15.06 34.3  31.85 16.   11.02  8.51 11.38 12.16 40.55 12.02\n 16.47 17.59 30.4  30.14 16.04 15.95 39.42 45.35  9.6  16.66 31.27 20.53\n 32.4  22.75 20.69  9.68  8.35 15.69 23.68 15.36  9.94 12.26 13.42 32.83\n 10.09 18.04 13.81 19.44 17.78 12.74 26.88 15.81 14.   22.49 32.68 11.59\n  8.58 21.16 15.04 18.43 48.27 12.76 20.27 16.29 20.76 26.86 11.61 18.26\n 13.51 13.42 18.29 25.56 25.21 12.54 24.01 16.82].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.model_selection import train_test_split, RandomizedSearchCV\n",
    "from sklearn.metrics import r2_score, mean_squared_error\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "# 데이터 불러오기\n",
    "tips = sns.load_dataset('tips')\n",
    "print(tips.info())\n",
    "\n",
    "# 특성과 타겟 분리\n",
    "y = tips['tip']\n",
    "X = tips['total_bill']\n",
    "\n",
    "# 훈련, 테스트 데이터 분리\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)\n",
    "\n",
    "# Hyperparameters\n",
    "max_depth = st.select_slider(\"Select max depth\", options=[i for i in range(2, 30)], value=(5, 10))\n",
    "min_samples_leaf = st.slider(\"Minimum samples leaf\", min_value=2, max_value=20)\n",
    "\n",
    "st.write('max_depth:', max_depth, 'min_samples_leat:', min_samples_leaf)\n",
    "\n",
    "random_search = {'max_depth': [i for i in range(max_depth[0], max_depth[1])],\n",
    "                 'min_samples_leaf': [min_samples_leaf]}\n",
    "\n",
    "clf = RandomForestRegressor()\n",
    "model = RandomizedSearchCV(estimator = clf, param_distributions = random_search, n_iter = 10, \n",
    "                               cv = 4, verbose= 1, random_state= 101, n_jobs = -1)\n",
    "model.fit(X_train,y_train)\n",
    "\n",
    "# 예측\n",
    "y_train_pred = model.predict(X_train)\n",
    "y_test_pred = model.predict(X_test)\n",
    "\n",
    "# 성능 평가\n",
    "test_rmse = mean_squared_error(y_test, y_test_pred, squared=False)\n",
    "r2 = r2_score(y_test, y_test_pred)\n",
    "\n",
    "# 그래프 그리기\n",
    "fig = go.Figure()\n",
    "fig.add_trace(\n",
    "    go.Scatter(x=X_test['total_bill'], y=y_test, mode='markers', name='test', marker=dict(color='red'))\n",
    ")\n",
    "fig.add_trace(\n",
    "    go.Scatter(x=X_test['total_bill'], y=y_test_pred, mode='markers', name='prediction', marker=dict(color='green'))\n",
    ")\n",
    "\n",
    "fig.update_layout(\n",
    "    title='Tip Prediction with Random Forest Regressor',\n",
    "    xaxis_title='Total Bill',\n",
    "    yaxis_title='Total',\n",
    "    annotations=[go.layout.Annotation(x=0.05, y=0.9, \n",
    "                                        text=f'Test RMSE: {test_rmse:.3f}<br>R2 Score: {r2:.3f}',\n",
    "                                        showarrow=False)]\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
